runtime: python
env: flexible
entrypoint: gunicorn -b :$PORT home:app

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"

api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: home.app
