runtime: python311
env: flex
entrypoint: gunicorn -b :$PORT home:app

runtime_config:
  operating_system: "ubuntu22"

api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: home.app

libraries:
  - name: flask
    version: 3.0.0
